// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace BMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200422134413_ChangeAircraftModel")]
    partial class ChangeAircraftModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BMS.Data.LoadingInstructions.LoadingInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HoldFivePieces")
                        .HasColumnType("int");

                    b.Property<int>("HoldFourPieces")
                        .HasColumnType("int");

                    b.Property<int>("HoldOnePieces")
                        .HasColumnType("int");

                    b.Property<int>("HoldThreePieces")
                        .HasColumnType("int");

                    b.Property<int>("HoldTwoPieces")
                        .HasColumnType("int");

                    b.Property<string>("OutboundFlightFlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OutboundFlightFlightNumber")
                        .IsUnique()
                        .HasFilter("[OutboundFlightFlightNumber] IS NOT NULL");

                    b.ToTable("LoadingInstructions");
                });

            modelBuilder.Entity("BMS.Data.Models.Aircraft", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AircraftBaggageHoldId")
                        .HasColumnType("int");

                    b.Property<int>("AircraftCabinId")
                        .HasColumnType("int");

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuelFormId")
                        .HasColumnType("int");

                    b.Property<string>("OutboundFlightFlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightFormId")
                        .HasColumnType("int");

                    b.HasKey("AircraftId");

                    b.HasIndex("OutboundFlightFlightNumber")
                        .IsUnique()
                        .HasFilter("[OutboundFlightFlightNumber] IS NOT NULL");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("BMS.Data.Models.AircraftBaggageHold", b =>
                {
                    b.Property<int>("BaggageHoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.HasKey("BaggageHoldId");

                    b.HasIndex("AircraftId")
                        .IsUnique();

                    b.ToTable("AircraftBaggageHolds");
                });

            modelBuilder.Entity("BMS.Data.Models.AircraftCabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId")
                        .IsUnique();

                    b.ToTable("AircraftCabins");
                });

            modelBuilder.Entity("BMS.Data.Models.ArrivalMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfMovement")
                        .HasColumnType("datetime2");

                    b.Property<string>("InboundFlightFlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OnBlockTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupplementaryInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TouchdownTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InboundFlightFlightNumber")
                        .IsUnique()
                        .HasFilter("[InboundFlightFlightNumber] IS NOT NULL");

                    b.ToTable("ArrivalMovements");
                });

            modelBuilder.Entity("BMS.Data.Models.BaggageHolds.AircraftBaggageHolds.Compartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaggageHoldId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPiecesInCompartment")
                        .HasColumnType("int");

                    b.Property<int>("MaxCompartmentWeight")
                        .HasColumnType("int");

                    b.Property<int>("PiecesToPutInCompartment")
                        .HasColumnType("int");

                    b.Property<int>("TotalWeightInCompartment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaggageHoldId");

                    b.ToTable("Compartments");
                });

            modelBuilder.Entity("BMS.Data.Models.Cabins.AircraftCabinZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AircraftCabinId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ZoneType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftCabinId");

                    b.ToTable("CabinZones");
                });

            modelBuilder.Entity("BMS.Data.Models.DepartureMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfMovement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OffBlockTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutboundFlightFlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupplementaryInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakeoffTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPAX")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OutboundFlightFlightNumber")
                        .IsUnique()
                        .HasFilter("[OutboundFlightFlightNumber] IS NOT NULL");

                    b.ToTable("DepartureMovements");
                });

            modelBuilder.Entity("BMS.Data.Models.FuelForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<double>("BlockFuel")
                        .HasColumnType("float");

                    b.Property<string>("CrewConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DryOperatingIndex")
                        .HasColumnType("float");

                    b.Property<double>("DryOperatingWeight")
                        .HasColumnType("float");

                    b.Property<string>("PilotInCommand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TakeoffFuel")
                        .HasColumnType("int");

                    b.Property<double>("TaxiFuel")
                        .HasColumnType("float");

                    b.Property<double>("TripFuel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId")
                        .IsUnique();

                    b.ToTable("FuelForms");
                });

            modelBuilder.Entity("BMS.Data.Models.InboundFlight", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ArrivalMovementId")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("STA")
                        .HasColumnType("datetime2");

                    b.HasKey("FlightNumber");

                    b.ToTable("InboundFlights");
                });

            modelBuilder.Entity("BMS.Data.Models.Messages.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InboundFlightFlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OutboundFlightFlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MessageId");

                    b.HasIndex("InboundFlightFlightNumber");

                    b.HasIndex("OutboundFlightFlightNumber");

                    b.ToTable("Messages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Message");
                });

            modelBuilder.Entity("BMS.Data.Models.OutboundFlight", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("BookedPAX")
                        .HasColumnType("int");

                    b.Property<int>("DepartureMovementId")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlingStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeparted")
                        .HasColumnType("bit");

                    b.Property<int>("LoadingInstructionId")
                        .HasColumnType("int");

                    b.Property<string>("RampAgentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("STD")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatMap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightNumber");

                    b.ToTable("OutboundFlights");
                });

            modelBuilder.Entity("BMS.Data.Models.Passenger", b =>
                {
                    b.Property<int>("PaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AircraftCabinZoneId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PaxId");

                    b.HasIndex("AircraftCabinZoneId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("BMS.Data.Models.Suitcase", b =>
                {
                    b.Property<string>("SuitcaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompartmentId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerPaxId")
                        .HasColumnType("int");

                    b.Property<int>("PaxId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("SuitcaseId");

                    b.HasIndex("CompartmentId");

                    b.HasIndex("PassengerPaxId");

                    b.ToTable("Suitcase");
                });

            modelBuilder.Entity("BMS.Data.WeightForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AircraftBasicWeight")
                        .HasColumnType("float");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<double>("MaximumLandingWeight")
                        .HasColumnType("float");

                    b.Property<double>("MaximumTakeoffWeight")
                        .HasColumnType("float");

                    b.Property<double>("MaximumZeroFuelWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId")
                        .IsUnique();

                    b.ToTable("WeightForms");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BMS.Data.Models.Messages.LoadDistributionMessage", b =>
                {
                    b.HasBaseType("BMS.Data.Models.Messages.Message");

                    b.Property<string>("CrewConfiguration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PAXChildren")
                        .HasColumnType("int");

                    b.Property<int>("PAXFemale")
                        .HasColumnType("int");

                    b.Property<int>("PAXInfants")
                        .HasColumnType("int");

                    b.Property<int>("PAXMale")
                        .HasColumnType("int");

                    b.Property<int>("TTLWeightInCPT1")
                        .HasColumnType("int");

                    b.Property<int>("TTLWeightInCPT2")
                        .HasColumnType("int");

                    b.Property<int>("TTLWeightInCPT4")
                        .HasColumnType("int");

                    b.Property<int>("TTLWeightInCPT5")
                        .HasColumnType("int");

                    b.Property<int>("TTlWeightINCPT3")
                        .HasColumnType("int");

                    b.Property<int>("TotalBaggagePieces")
                        .HasColumnType("int");

                    b.Property<int>("TotalCargo")
                        .HasColumnType("int");

                    b.Property<int>("TotalPax")
                        .HasColumnType("int");

                    b.Property<int>("TotalWeightInAllCompartments")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("LoadDistributionMessage");
                });

            modelBuilder.Entity("BMS.Data.LoadingInstructions.LoadingInstruction", b =>
                {
                    b.HasOne("BMS.Data.Models.OutboundFlight", "OutboundFlight")
                        .WithOne("LoadingInstruction")
                        .HasForeignKey("BMS.Data.LoadingInstructions.LoadingInstruction", "OutboundFlightFlightNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BMS.Data.Models.Aircraft", b =>
                {
                    b.HasOne("BMS.Data.Models.OutboundFlight", "OutboundFlight")
                        .WithOne("Aircraft")
                        .HasForeignKey("BMS.Data.Models.Aircraft", "OutboundFlightFlightNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BMS.Data.Models.AircraftBaggageHold", b =>
                {
                    b.HasOne("BMS.Data.Models.Aircraft", "Aircraft")
                        .WithOne("BaggageHold")
                        .HasForeignKey("BMS.Data.Models.AircraftBaggageHold", "AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.Models.AircraftCabin", b =>
                {
                    b.HasOne("BMS.Data.Models.Aircraft", "Aircraft")
                        .WithOne("Cabin")
                        .HasForeignKey("BMS.Data.Models.AircraftCabin", "AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.Models.ArrivalMovement", b =>
                {
                    b.HasOne("BMS.Data.Models.InboundFlight", "InboundFlight")
                        .WithOne("ArrivalMovement")
                        .HasForeignKey("BMS.Data.Models.ArrivalMovement", "InboundFlightFlightNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BMS.Data.Models.BaggageHolds.AircraftBaggageHolds.Compartment", b =>
                {
                    b.HasOne("BMS.Data.Models.AircraftBaggageHold", "BaggageHold")
                        .WithMany("Compartments")
                        .HasForeignKey("BaggageHoldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.Models.Cabins.AircraftCabinZone", b =>
                {
                    b.HasOne("BMS.Data.Models.AircraftCabin", "Cabin")
                        .WithMany("Zones")
                        .HasForeignKey("AircraftCabinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.Models.DepartureMovement", b =>
                {
                    b.HasOne("BMS.Data.Models.OutboundFlight", "OutboundFlight")
                        .WithOne("DepartureMovement")
                        .HasForeignKey("BMS.Data.Models.DepartureMovement", "OutboundFlightFlightNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BMS.Data.Models.FuelForm", b =>
                {
                    b.HasOne("BMS.Data.Models.Aircraft", "Aircraft")
                        .WithOne("FuelForm")
                        .HasForeignKey("BMS.Data.Models.FuelForm", "AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.Models.Messages.Message", b =>
                {
                    b.HasOne("BMS.Data.Models.InboundFlight", "Inbound")
                        .WithMany("InboundMessages")
                        .HasForeignKey("InboundFlightFlightNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BMS.Data.Models.OutboundFlight", "Outbound")
                        .WithMany("OutboundMessages")
                        .HasForeignKey("OutboundFlightFlightNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.Models.Passenger", b =>
                {
                    b.HasOne("BMS.Data.Models.Cabins.AircraftCabinZone", "Zone")
                        .WithMany("Passengers")
                        .HasForeignKey("AircraftCabinZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.Models.Suitcase", b =>
                {
                    b.HasOne("BMS.Data.Models.BaggageHolds.AircraftBaggageHolds.Compartment", "Compartment")
                        .WithMany("Suitcases")
                        .HasForeignKey("CompartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BMS.Data.Models.Passenger", "Passenger")
                        .WithMany("Suitcases")
                        .HasForeignKey("PassengerPaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Data.WeightForm", b =>
                {
                    b.HasOne("BMS.Data.Models.Aircraft", "Aircraft")
                        .WithOne("WeightForm")
                        .HasForeignKey("BMS.Data.WeightForm", "AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
